# Generated by Django 5.1.4 on 2025-06-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_profile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='win_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='level',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
